#!/usr/bin/env python

import rospy
import sys
from std_msgs.msg import String
from sensor_msgs.msg import Image


def recognize_faces_callback(data):
    name = "Unknown" 

    pub.publish(name)

if __name__ == "__main__":
    try:
        rospy.init_node('stream_face_recognizer')

        pub = rospy.Publisher('recognized_faces', String, queue_size=10)

        camera_stream_topic = rospy.get_param(rospy.resolve_name("~camera_stream_topic"))
        rospy.Subscriber(camera_stream_topic, Image, recognize_faces_callback)
        print("Ready to recognize faces in video stream")
        rospy.spin()

    except rospy.ROSInterruptException as e:
        print(e)
